### ISSUE TITLE
Breaking change on 0.1.2 -> 0.2.0

### ISSUE THREAD

**Issue by Sealos** [tensor-hq/eksctl-helm-action#4]
Hi, thanks for the great library,

We just updated it to the new version, but our old workflows don't work anymore, as the image input is now required, can this be documented in the example what values to set?

Thanks!

```
Error:
Download action repository 'tensor-hq/eksctl-helm-action@v0.2.0' (SHA:9e4d2599036c0bea577da7acbfa08d58a937f2a5)
Error: tensor-hq/eksctl-helm-action/v0.2.0/action.yml (Line: 29, Col: 10): Unrecognized named-value: 'input'. Located at position 1 within expression: input.image
Error: Failed to load tensor-hq/eksctl-helm-action/v0.2.0/action.yml
```

**Comment by wehappyfew** [comment]
Yeah, me too

**Comment by fsteinke** [comment]
looks like a simple typo in https://github.com/tensor-hq/eksctl-helm-action/blob/main/action.yml#L29 which is likely supposed to be

```
  image: ${{ inputs.image }}
```

**Comment by seslly** [comment]
simple fix, apologies for not catching this sooner
